### PR TITLE
Getting path for web image from db, tile layout wdg

### PR DESCRIPTION
**Pull request by listyque**
Fix for tiled layout, where web path generated not from file and database.

### CODE REVIEW

**Comment by CeltonMcGrath** [comment]
Why are you trying to do this? 

Currently, the file path is retrieved directly from the XML. Your method requires an extra database lookup.

Thanks,
Celton

**Comment by listyque** [comment]
> Why are you trying to do this?

Looks like it is related to my filenaming setup. I have previews and icons in their own sub-dirs, like this: asset/__preview/web/filtename.jpg. And this sub dirs does not taken into account when get_web_path_by_type called.
You can Ignore this request if you think it is unnecessary
Btw i faced this problem only with tile layout, other widgets seems to querying names from files table

**Comment by listyque** [comment]
I have expression in my naming conversion {sobject.relative_dir}/{@CASE( @GET(file.type) == 'web', '__preview/web')} and all my web files goes to different directory. And TileWdg cant handle this path by default

**Comment by CeltonMcGrath** [comment]
Thank you for the information. What are you suggesting is correct for your setup.

However, we are planning on improving of the performance of the TileLayoutWdg by preprocessing the thumbnails. With this change, we will grab the file paths from the database instead of XML.

This means your change will become obsolete. We will try to make this change soon.

Thanks for submitting this, and I hope this helps.

**Comment by listyque** [comment]
This is good news for me :)
Also i have some changes in code snapshot.py (2 lines) and naming.py (1 line). This changes let tactic handle dir naming correctly per file node, so user can use file.type and others. I think it can be useful, as i saw users asked for this in tactic community forum (RIP). Should i make a PR?

**Comment by CeltonMcGrath** [comment]
I am intrigued - please submit a PR.

Thank you

**Pull request closed without merging**
