### PR TITLE
Auto pending, check if all input processes are completed

### PR DESCRIPTION
**Pull request by diegocortassa**
when a process is completed before setting an output process to pending we have to check if all of his input processes are completed

### CODE REVIEW

**Comment by oboreo** [comment]
This is a great suggestion. but it's too task centric and it's happening in the handle_complete() which is not the best place.. cuz one would need to add the same logic to all handle_complete().. A more ideal place is to call check_inputs() in ProcessPendingTrigger. Of course def check_inputs() needs to be moved to BaseProcessTriggger.

**Comment by diegocortassa** [comment]
To close and clean up these old PR I reread the code from src/pyasm/command/workflow.py and found out this feature is already implemented but disabled (commented out, see my.check_inputs() calls in handle_pending() from BaseWorkflowNodeHandler, WorkflowManualNodeHandlerand  WorkflowActionNodeHandler classes) I uncommented the calls and tested them, it seems to me everything is working ok and I see no reason why they are disabled. @oboreo can I send a new PR to enable these calls? At the moment tactic automatically sets a task to pending regardless of whether all of it's input tasks are completed incorrectly pushing the pipeline forward.

**Comment by remkonoteboom** [comment]
Sorry, Diego.  I missed this.  I think there has been a bunch of confusion on this, so let's start over. 

I have looked it over a bit and yes, it seems a bit strange that this is commented out.  I think it had to do with the introduction of using the messages to store the state of the pipeline and the overhead associated with that.  Not sure how it impacted performance because it is a tad inefficient (it does an sql call per input).  It's not serious, so we may be able to overlook that.

Also, there is another function that is called: check_complete_inputs and the difference between this and check_inputs did cause some confusion.  However, this checks before "complete" not pending and it checks for hierarchical dependencies.  I think both functions are needed.

So, yes, submit a pull request because you have tested it.  I will take what you have and make sure the commented out unit test works.

**Comment by diegocortassa** [comment]
Ok Remko, tomorrow I will open another PR. Thanks

**Comment by diegocortassa** [comment]
Closing this PR because superseded by #815

**Comment by diegocortassa** [comment]
Closing this PR because superseded by #815

**Pull request closed without merging**
