### PR TITLE
Unicode related fix for Task Status Triggers

### PR DESCRIPTION
**Pull request by listyque**
If task status is not string, but unicode we need this fix.

### CODE REVIEW

**Comment by CeltonMcGrath** [comment]
Hi @listyque,

Thanks for submitting this. Best practice within TACTIC with Python 2.7 is to use strings instead of unicode. Why are you setting the task status as a unicode string?

Further, we are working towards Python3 compatibility, where there are no issues with strings and unicode.

Also, we have recently restarted the TACTIC Community Forum.
Feel free to sign up here:
forum.southpawtech.com

**Comment by listyque** [comment]
image
In our Poroject all our Tasks statuses are in russian, so everything fine with it, except triggers.
Since my server using python 2.7 i had to do this changes to get things fixed.
About the community! It is really good news, i missed it so much!

**Comment by CeltonMcGrath** [comment]
@listyque 

Feel free to leave this pull request open. I intend on resolving this within the next week.

**Comment by listyque** [comment]
> @listyque
> 
> Feel free to leave this pull request open. I intend on resolving this within the next week.

I found a bug related to this change.
It broke dynamic updates. Still searching for the solution.

For unknown reasot js cant get right task id
("@GET(sthpw/task['id','true'].assigned)", {   'single': True})
ERROR: do_query error:  invalid input syntax for integer: "true"
LINE 1: ... FROM "sthpw"."public"."task" WHERE "task"."id" = 'true' AND...
                                                             ^
SELECT "sthpw"."public"."task".* FROM "sthpw"."public"."task" WHERE "task"."id" = 'true' AND ("task"."s_status" != 'retired' or "task"."s_status" is NULL) ORDER BY "task"."search_type", "task"."search_code"

**Comment by CeltonMcGrath** [comment]
@listyque 

This is unfortunately not surprising. Quite a bit of work has been put into TACTIC to handle unicode strings with encode and decode.

I would recommend fixing this from the source. Where ever the task status is being passed, ensure that it is encoded and decoded properly. However, depending on the depth of the issue, it might be worth trying Python 3. I have a feeling this issue would be resolved in Python 3.

We are nearing full support of Python 3 for TACTIC 4.7.

**Comment by listyque** [comment]
> @listyque
> 
> This is unfortunately not surprising. Quite a bit of work has been put into TACTIC to handle unicode strings with encode and decode.
> 
> I would recommend fixing this from the source. Where ever the task status is being passed, ensure that it is encoded and decoded properly. However, depending on the depth of the issue, it might be worth trying Python 3. I have a feeling this issue would be resolved in Python 3.
> 
> We are nearing full support of Python 3 for TACTIC 4.7.

This would be better if task statuses have the same table as "process" so we can have labels, and not change actual status in russian, this would theoretically require less str to unicode encodings...

**Comment by listyque** [comment]
> We are nearing full support of Python 3 for TACTIC 4.7.

I found that this is because of:
class Process(Base):
    def __str__(my):
        return my.get_name()

and there is no unicode handle. So when tasks dynamically fetch for data it returns 'true' in cases when node is 0
Ohh... %)
Still not found how to handle it

**Pull request closed without merging**
